### ISSUE TITLE
is_write_qry is catching non-write queries

### ISSUE THREAD

**Issue by arredond** [GeographicaGS/Longitude#20]
Currently, Longitude checks whether a query is a write query by searching for words in the query string (create, update, etc). 
```python
def _is_write_query(sql_query):
    """
    Check if query is a write query
    """
    write_cmds = 'drop|delete|insert|update|grant|execute|perform|create|begin|commit|alter'
    is_write = re.search(write_cmds, sql_query.lower())
    if is_write:
        return True
```

This leads to false positives when these words are contained inside quotation marks or are part of other words, such as:
```sql
SELECT id FROM users WHERE username = 'create_user_test';
```
Some improvements would include checking whether these reserved words are inside others or inside quotation mark.

**Comment by danibishop** [comment]
This could be semi-accomplised using some parser like [this one](https://sqlparse.readthedocs.io/en/latest/). The issue is that it is extremely hard to determine if a query will need to ```commit``` or not (accordingly to a discussion I had with @cayetanobv )

**Comment by josemazo** [comment]
This is impossible to achieve because we could be calling a PL/pgSQL that writes anything. The only solution it's to trust the `write_query` parameter.
